SELECT
    "court".name,
    "court".player_qty,
    "court".description,
    "court".modality,
    "court".rating,
    "court".address_id,
    "court".id,
    "address".street,
    "address".number,
    "address".zipcode,
    "address".complement,
    "address".block,
    "address".city_district,
    "address".city,
    "address".state,
    "address".country,
    "address".latitude,
    "address".longitude,
    "address".id,
    "slot".reservation_datetime,
    "slot".price,
    "slot".cancellation_datetime,
    "slot".user_id,
    "slot".court_id,
    "slot".id,
    string_agg(amenity.id::text, ', ') as amenities
FROM joga_ai.slot
INNER JOIN joga_ai.court ON slot.court_id = court.id
INNER JOIN joga_ai.address ON court.address_id = address.id
LEFT JOIN joga_ai.court_has_amenity ON court.id = court_has_amenity.court_id
INNER JOIN joga_ai.amenity ON court_has_amenity.amenity_id = amenity.id
WHERE slot.user_id IS NULL AND slot.cancellation_datetime IS NULL AND court.address_id IS NOT NULL
GROUP BY
    "court".name,
    "court".player_qty,
    "court".description,
    "court".modality,
    "court".rating,
    "court".address_id,
    "court".id,
    "address".street,
    "address".number,
    "address".zipcode,
    "address".complement,
    "address".block,
    "address".city_district,
    "address".city,
    "address".state,
    "address".country,
    "address".latitude,
    "address".longitude,
    "address".id,
    "slot".reservation_datetime,
    "slot".price,
    "slot".cancellation_datetime,
    "slot".user_id,
    "slot".court_id,
    "slot".id;
